version: '3.8'

services:
  db:
    image: mariadb:10.6
    platform: linux/arm64/v8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql # Initialization script

  backend:
    build:
      context: ./backend
    ports:
      - "8800:8800"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: test
    depends_on:
      - db

  frontend:
    environment:
      - PORT=5173
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db-data:

